import Link from 'next/link'
import Head from 'next/head'
function Events () {
	return <h1>All events
			<Head>
				<title>ULTeam | Events</title>
        		<meta name="description" content="Generated by create next app" />
			</Head>
			<Link href="/">
				<a>
					Home
				</a>
			</Link>
			</h1>
}


export default Events